apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  labels:
    app: python-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: python-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: python-app # Assumes you have built an image with this name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            # These values point to the Kubernetes Service for the Node.js app
            - name: NODE_SERVICE_HOST
              value: "node-app-svc"
            - name: NODE_SERVICE_PORT
              value: "6000"
