version: "3.8"

services:
  python-app:
    image: python-app
    container_name: python-app
    environment:
      - NODE_SERVER=node-app   
    ports:
      - "7000:5000"
    depends_on:
      - node-app

  node-app:
    image: node-app
    container_name: node-app
    environment:
      - TARGET_SERVER=spring-app   
    ports:
      - "8000:6000"
    depends_on:
      - spring-app
    volumes:
      - node-csv:/app/csv
      - node-xml:/app/xml

  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "9001:6001"
    volumes:
      - spring-json:/app

volumes:
  node-csv:
  node-xml:
  spring-json:
